netty.server:
  servicing.address: 127.0.0.1:9090,127.0.0.1:9091
  selfport: 9090
  # self port used to connect other netty server
  local.port: 12088
  white.list: 127.0.0.1
  backlog: 1024



socketio:
  starting.port: 9092

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  rabbitmq:
      host: localhost
      port: 5672
      username: admin
      password: admin
      defaultExchange: servant
  redis:
    host: localhost
    port: 6379



mongo:
  chatmessage:
    collectionName: user_chat_history
