netty.server:
  servicing.address: 127.0.0.1:9090,127.0.0.1:9091
  selfport: 9091
  # self port used to connect other netty server
  local.port: 12089
  white.list: 127.0.0.1
  backlog: 1024



socketio:
  starting.port: 9093

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: admin
      password: admin
      defaultExchange: servant
  redis:
    host: 127.0.0.1
    port: 6379


mongo:
  chatmessage:
    collectionName: user_chat_history
server:
  port: 8081
